// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"github.com/gabriel-vasile/mimetype"
	"github.com/goplus/community/internal/core"
	"github.com/goplus/community/translation"
	"github.com/goplus/yap"
	"github.com/joho/godotenv"
	_ "github.com/joho/godotenv/autoload"
	"github.com/liuscraft/gop-casdoor-account-sdk"
	"github.com/qiniu/x/xlog"
	"golang.org/x/text/language"
	"io"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const _ = true
const (
	limitConst      = 10
	mediaLimitConst = 8
	firstConst      = "1"
	labelConst      = "article"
)

type community struct {
	yap.App
	community *core.Community
	trans     *translation.Engine
	domain    string
	htmlUrl   string
}
//line cmd/gopcomm/community_yap.gox:37
func (this *community) MainEntry() {
//line cmd/gopcomm/community_yap.gox:37:1
	todo := context.TODO()
//line cmd/gopcomm/community_yap.gox:38:1
	xLog := xlog.New("")
//line cmd/gopcomm/community_yap.gox:42:1
	this.Static__0("/static")
//line cmd/gopcomm/community_yap.gox:44:1
	this.Get("/success", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:45:1
		ctx.Yap__1("2xx", map[string]interface{}{})
	})
//line cmd/gopcomm/community_yap.gox:48:1
	this.Get("/error", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:49:1
		var user *core.User
//line cmd/gopcomm/community_yap.gox:50:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:51:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:52:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:55:1
		ctx.Yap__1("4xx", map[string]*core.User{"User": user})
	})
//line cmd/gopcomm/community_yap.gox:60:1
	this.Get("/failed", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:61:1
		var user *core.User
//line cmd/gopcomm/community_yap.gox:62:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:63:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:64:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:67:1
		ctx.Yap__1("5xx", map[string]*core.User{"User": user})
	})
//line cmd/gopcomm/community_yap.gox:73:1
	this.Get("/", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:74:1
		// Get User Info
		var user *core.User
//line cmd/gopcomm/community_yap.gox:76:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:77:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:78:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:81:1
		articles, next, err := this.community.ListArticle(todo, core.MarkBegin, limitConst, "", labelConst)
//line cmd/gopcomm/community_yap.gox:82:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:83:1
			xLog.Error("get article error:", err)
		}
//line cmd/gopcomm/community_yap.gox:86:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:87:1
			xLog.Error("json marshal error:", err)
		}
//line cmd/gopcomm/community_yap.gox:89:1
		ctx.Yap__1("home", map[string]interface{}{"User": user, "Items": articles, "Next": next})
	})
//line cmd/gopcomm/community_yap.gox:99:1
	this.Get("/article/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:102:1
		uid := ""
//line cmd/gopcomm/community_yap.gox:104:1
		var user *core.User
//line cmd/gopcomm/community_yap.gox:105:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:106:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:107:1
			user, err = this.community.GetUser(token.Value)
//line cmd/gopcomm/community_yap.gox:108:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:109:1
				xLog.Error("get user error:", err)
//line cmd/gopcomm/community_yap.gox:110:1
				return
			}
//line cmd/gopcomm/community_yap.gox:112:1
			uid = user.Id
		}
//line cmd/gopcomm/community_yap.gox:115:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:116:1
		platform := ctx.Param("platform")
//line cmd/gopcomm/community_yap.gox:117:1
		ip := this.community.GetClientIP(ctx.Request)
//line cmd/gopcomm/community_yap.gox:118:1
		this.community.ArticleLView(todo, id, ip, uid, platform)
//line cmd/gopcomm/community_yap.gox:119:1
		article, err := this.community.Article(todo, id)
//line cmd/gopcomm/community_yap.gox:120:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:121:1
			xLog.Error("get article error:", err)
//line cmd/gopcomm/community_yap.gox:122:1
			return
		}
//line cmd/gopcomm/community_yap.gox:124:1
		likeState, err := this.community.ArticleLikeState(todo, uid, id)
//line cmd/gopcomm/community_yap.gox:125:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:126:1
			xLog.Error("article state err:", err)
//line cmd/gopcomm/community_yap.gox:127:1
			return
		}
//line cmd/gopcomm/community_yap.gox:130:1
		ctx.Yap__1("article", map[string]interface{}{"User": user, "Article": article, "LikeState": likeState})
	})
//line cmd/gopcomm/community_yap.gox:137:1
	this.Get("/add", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:138:1
		var user *core.User
//line cmd/gopcomm/community_yap.gox:139:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:140:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:141:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:143:1
		ctx.Yap__1("edit", map[string]*core.User{"User": user})
	})
//line cmd/gopcomm/community_yap.gox:148:1
	this.Get("/edit/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:149:1
		var user *core.User
//line cmd/gopcomm/community_yap.gox:150:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:151:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:152:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:155:1
		uid := user.Id
//line cmd/gopcomm/community_yap.gox:156:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:157:1
		if id != "" {
//line cmd/gopcomm/community_yap.gox:158:1
			editable, err := this.community.CanEditable(todo, uid, id)
//line cmd/gopcomm/community_yap.gox:159:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:160:1
				xLog.Error("can editable error:", err)
//line cmd/gopcomm/community_yap.gox:161:1
				http.Redirect(ctx.ResponseWriter, ctx.Request, "/error", http.StatusTemporaryRedirect)
			}
//line cmd/gopcomm/community_yap.gox:163:1
			if !editable {
//line cmd/gopcomm/community_yap.gox:164:1
				xLog.Error("no permissions")
//line cmd/gopcomm/community_yap.gox:165:1
				http.Redirect(ctx.ResponseWriter, ctx.Request, "/error", http.StatusTemporaryRedirect)
			}
//line cmd/gopcomm/community_yap.gox:167:1
			article, err := this.community.Article(todo, id)
//line cmd/gopcomm/community_yap.gox:168:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:169:1
				xLog.Error("get article error:", err)
//line cmd/gopcomm/community_yap.gox:170:1
				http.Redirect(ctx.ResponseWriter, ctx.Request, "/error", http.StatusTemporaryRedirect)
			}
//line cmd/gopcomm/community_yap.gox:173:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:174:1
				xLog.Error("json marshal error:", err)
//line cmd/gopcomm/community_yap.gox:175:1
				http.Redirect(ctx.ResponseWriter, ctx.Request, "/error", http.StatusTemporaryRedirect)
			}
//line cmd/gopcomm/community_yap.gox:177:1
			ctx.Yap__1("edit", map[string]interface{}{"User": user, "Article": article})
		}
	})
//line cmd/gopcomm/community_yap.gox:184:1
	this.Get("/search", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:185:1
		searchValue := ctx.Param("value")
//line cmd/gopcomm/community_yap.gox:186:1
		label := ctx.Param("label")
//line cmd/gopcomm/community_yap.gox:187:1
		if label == "" {
//line cmd/gopcomm/community_yap.gox:188:1
			label = "article"
		}
//line cmd/gopcomm/community_yap.gox:191:1
		// todo middleware
		var user *core.User
//line cmd/gopcomm/community_yap.gox:193:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:194:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:195:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:198:1
		articles, next, err := this.community.ListArticle(todo, core.MarkBegin, limitConst, searchValue, label)
//line cmd/gopcomm/community_yap.gox:199:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:200:1
			xLog.Error("get article error:", err)
		}
//line cmd/gopcomm/community_yap.gox:203:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:204:1
			xLog.Error("json marshal error:", err)
		}
//line cmd/gopcomm/community_yap.gox:206:1
		ctx.Yap__1("home", map[string]interface{}{"User": user, "Items": articles, "Value": searchValue, "Next": next, "Tab": label})
	})
//line cmd/gopcomm/community_yap.gox:218:1
	this.Get("/api/article/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:219:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:220:1
		article, err := this.community.Article(todo, id)
//line cmd/gopcomm/community_yap.gox:221:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:222:1
			xLog.Error("get article error:", err)
//line cmd/gopcomm/community_yap.gox:223:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "get article failed"})
		}
//line cmd/gopcomm/community_yap.gox:228:1
		ctx.Json__1(map[string]interface{}{"code": 200, "data": article})
	})
//line cmd/gopcomm/community_yap.gox:234:1
	this.Delete("/api/article/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:235:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:236:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:237:1
		uid, err := this.community.ParseJwtToken(token.Value)
//line cmd/gopcomm/community_yap.gox:238:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:239:1
			xLog.Error("token parse error")
//line cmd/gopcomm/community_yap.gox:240:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:245:1
		err = this.community.DeleteArticle(todo, uid, id)
//line cmd/gopcomm/community_yap.gox:246:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:247:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "delete failed"})
		} else {
//line cmd/gopcomm/community_yap.gox:252:1
			ctx.Json__1(map[string]interface{}{"code": 200, "msg": "delete success"})
		}
	})
//line cmd/gopcomm/community_yap.gox:259:1
	this.Get("/api/articles", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:260:1
		from := ctx.Param("from")
//line cmd/gopcomm/community_yap.gox:261:1
		limit := ctx.Param("limit")
//line cmd/gopcomm/community_yap.gox:262:1
		searchValue := ctx.Param("value")
//line cmd/gopcomm/community_yap.gox:263:1
		label := ctx.Param("label")
//line cmd/gopcomm/community_yap.gox:265:1
		limitInt, err := strconv.Atoi(limit)
//line cmd/gopcomm/community_yap.gox:266:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:267:1
			limitInt = limitConst
		}
//line cmd/gopcomm/community_yap.gox:270:1
		articles, next, err := this.community.ListArticle(todo, from, limitInt, searchValue, label)
//line cmd/gopcomm/community_yap.gox:271:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:272:1
			xLog.Error("get article error:", err)
//line cmd/gopcomm/community_yap.gox:273:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "get article failed"})
		}
//line cmd/gopcomm/community_yap.gox:278:1
		ctx.Json__1(map[string]interface{}{"code": 200, "items": articles, "next": next, "value": searchValue})
	})
//line cmd/gopcomm/community_yap.gox:286:1
	this.Post("/api/article/commit", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:287:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:288:1
		content := ctx.Param("content")
//line cmd/gopcomm/community_yap.gox:289:1
		title := ctx.Param("title")
//line cmd/gopcomm/community_yap.gox:290:1
		tags := ctx.Param("tags")
//line cmd/gopcomm/community_yap.gox:291:1
		abstract := ctx.Param("abstract")
//line cmd/gopcomm/community_yap.gox:292:1
		label := ctx.Param("label")
//line cmd/gopcomm/community_yap.gox:293:1
		trans, err := strconv.ParseBool(ctx.Param("trans"))
//line cmd/gopcomm/community_yap.gox:294:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:295:1
			xLog.Error("parse bool error:", err)
		}
//line cmd/gopcomm/community_yap.gox:298:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:299:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:300:1
			xLog.Info("token", err)
//line cmd/gopcomm/community_yap.gox:301:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "no token"})
		}
//line cmd/gopcomm/community_yap.gox:306:1
		uid, err := this.community.ParseJwtToken(token.Value)
//line cmd/gopcomm/community_yap.gox:307:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:308:1
			xLog.Info("uid", err)
//line cmd/gopcomm/community_yap.gox:309:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:314:1
		article := &core.Article{ArticleEntry: core.ArticleEntry{ID: id, Title: title, UId: uid, Cover: ctx.Param("cover"), Tags: tags, Abstract: abstract, Label: label}, Content: content, Trans: trans, VttId: ctx.Param("vtt_id")}
//line cmd/gopcomm/community_yap.gox:330:1
		if trans {
//line cmd/gopcomm/community_yap.gox:331:1
			article, _ = this.community.TranslateArticle(todo, article)
		}
//line cmd/gopcomm/community_yap.gox:334:1
		id, err = this.community.PutArticle(todo, uid, article)
//line cmd/gopcomm/community_yap.gox:335:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:336:1
			xLog.Info(err)
//line cmd/gopcomm/community_yap.gox:337:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "add failed"})
		}
//line cmd/gopcomm/community_yap.gox:342:1
		ctx.Json__1(map[string]interface{}{"code": 200, "data": id})
	})
//line cmd/gopcomm/community_yap.gox:351:1
	this.Get("/user/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:352:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:354:1
		userClaim, err := this.community.GetUserClaim(id)
//line cmd/gopcomm/community_yap.gox:355:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:356:1
			xLog.Error("get current user error:", err)
		}
//line cmd/gopcomm/community_yap.gox:358:1
		// get user by token
		var user *core.User
//line cmd/gopcomm/community_yap.gox:360:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:361:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:362:1
			user, _ = this.community.GetUser(token.Value)
		}
//line cmd/gopcomm/community_yap.gox:365:1
		items, total, err := this.community.GetArticlesByUid(todo, id, firstConst, mediaLimitConst)
//line cmd/gopcomm/community_yap.gox:366:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:367:1
			xLog.Error("get article list error:", err)
		}
//line cmd/gopcomm/community_yap.gox:370:1
		isAdmin, err := this.community.IsAdmin(id)
//line cmd/gopcomm/community_yap.gox:371:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:372:1
			xLog.Error("check admin error:", err)
		}
//line cmd/gopcomm/community_yap.gox:374:1
		ctx.Yap__1("user", map[string]interface{}{"Id": id, "CurrentUser": userClaim, "User": user, "Items": items, "Total": total, "IsAdmin": isAdmin})
	})
//line cmd/gopcomm/community_yap.gox:384:1
	this.Get("/user/edit", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:385:1
		var user *core.User
//line cmd/gopcomm/community_yap.gox:386:1
		var uid string
//line cmd/gopcomm/community_yap.gox:387:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:388:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:389:1
			user, err = this.community.GetUser(token.Value)
//line cmd/gopcomm/community_yap.gox:390:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:391:1
				xLog.Error("get user error:", err)
			}
//line cmd/gopcomm/community_yap.gox:393:1
			uid = user.Id
		}
//line cmd/gopcomm/community_yap.gox:395:1
		userClaim, err := this.community.GetUserClaim(uid)
//line cmd/gopcomm/community_yap.gox:396:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:397:1
			xLog.Error("get current user error:", err)
		}
//line cmd/gopcomm/community_yap.gox:399:1
		gac, err := gopaccountsdk.GetClient(token.Value)
//line cmd/gopcomm/community_yap.gox:400:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:401:1
			xLog.Info("gac", err)
//line cmd/gopcomm/community_yap.gox:402:1
			http.Redirect(ctx.ResponseWriter, ctx.Request, "/error", http.StatusTemporaryRedirect)
		}
//line cmd/gopcomm/community_yap.gox:404:1
		appInfo, err := this.community.GetApplicationInfo()
//line cmd/gopcomm/community_yap.gox:405:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:406:1
			xLog.Error("get application info error:", err)
//line cmd/gopcomm/community_yap.gox:407:1
			http.Redirect(ctx.ResponseWriter, ctx.Request, "/error", http.StatusTemporaryRedirect)
		}
//line cmd/gopcomm/community_yap.gox:409:1
		providers := gac.GetProviders()
//line cmd/gopcomm/community_yap.gox:411:1
		ctx.Yap__1("user_edit", map[string]interface{}{"User": user, "CurrentUser": userClaim, "Application": appInfo, "Binds": gac.GetProviderBindStatus(), "casdoorUrl": gopaccountsdk.GetCasdoorEndPoint(), "providers": providers})
	})
//line cmd/gopcomm/community_yap.gox:424:1
	this.Put("/api/user", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:425:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:426:1
		uid, err := this.community.ParseJwtToken(token.Value)
//line cmd/gopcomm/community_yap.gox:427:1
		user := &core.UserInfo{Id: uid, Name: ctx.Param("name"), Birthday: ctx.Param("birthday"), Gender: ctx.Param("gender"), Phone: ctx.Param("phone"), Email: ctx.Param("email"), Avatar: ctx.Param("avatar"), Owner: ctx.Param("owner"), DisplayName: ctx.Param("displayName")}
//line cmd/gopcomm/community_yap.gox:439:1
		_, err = this.community.UpdateUser(user)
//line cmd/gopcomm/community_yap.gox:440:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:441:1
			xLog.Info(err)
//line cmd/gopcomm/community_yap.gox:442:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "update failed"})
		}
//line cmd/gopcomm/community_yap.gox:447:1
		ctx.Json__1(map[string]int{"code": 200})
	})
//line cmd/gopcomm/community_yap.gox:452:1
	this.Get("/api/users", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:453:1
		// get user by token
		var user *core.User
//line cmd/gopcomm/community_yap.gox:455:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:456:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:457:1
			casdoorUser, _ := this.community.GetUser(token.Value)
//line cmd/gopcomm/community_yap.gox:458:1
			user = &core.User{Id: casdoorUser.Id}
		} else {
//line cmd/gopcomm/community_yap.gox:462:1
			xLog.Error("get token error:", err)
//line cmd/gopcomm/community_yap.gox:463:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "get token failed", "users": nil, "next": 1})
		}
//line cmd/gopcomm/community_yap.gox:471:1
		from := ctx.Param("from")
//line cmd/gopcomm/community_yap.gox:472:1
		limit := ctx.Param("limit")
//line cmd/gopcomm/community_yap.gox:473:1
		fromInt, err := strconv.Atoi(from)
//line cmd/gopcomm/community_yap.gox:474:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:475:1
			fromInt = 1
		}
//line cmd/gopcomm/community_yap.gox:477:1
		limitInt, err := strconv.Atoi(limit)
//line cmd/gopcomm/community_yap.gox:478:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:479:1
			limitInt = limitConst
		}
//line cmd/gopcomm/community_yap.gox:483:1
		userAuth, err := this.community.GetUserAuthById(user.Id)
//line cmd/gopcomm/community_yap.gox:484:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:485:1
			xLog.Error("get current user auth error:", err)
		}
//line cmd/gopcomm/community_yap.gox:488:1
		if !userAuth.Status {
//line cmd/gopcomm/community_yap.gox:489:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "auth failed", "items": nil, "total": 10, "next": 1})
		}
//line cmd/gopcomm/community_yap.gox:498:1
		users, next, err := this.community.ListPageUsers(fromInt, limitInt)
//line cmd/gopcomm/community_yap.gox:499:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:500:1
			xLog.Error("get users error:", err)
//line cmd/gopcomm/community_yap.gox:501:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "get users failed", "items": nil, "total": 10, "next": 1})
		}
//line cmd/gopcomm/community_yap.gox:510:1
		ctx.Json__1(map[string]interface{}{"code": 200, "msg": "ok", "items": users, "total": len(users), "next": next})
	})
//line cmd/gopcomm/community_yap.gox:519:1
	this.Put("/api/user/public", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:520:1
		// get user by token
		var user *core.User
//line cmd/gopcomm/community_yap.gox:522:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:523:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:524:1
			casdoorUser, _ := this.community.GetUser(token.Value)
//line cmd/gopcomm/community_yap.gox:525:1
			user = &core.User{Id: casdoorUser.Id}
		} else {
//line cmd/gopcomm/community_yap.gox:529:1
			xLog.Error("get token error:", err)
//line cmd/gopcomm/community_yap.gox:530:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "get token failed", "users": nil, "next": 1})
		}
//line cmd/gopcomm/community_yap.gox:539:1
		userAuth, err := this.community.GetUserAuthById(user.Id)
//line cmd/gopcomm/community_yap.gox:540:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:541:1
			xLog.Error("get current user auth error:", err)
		}
//line cmd/gopcomm/community_yap.gox:544:1
		if !userAuth.Status {
//line cmd/gopcomm/community_yap.gox:545:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "auth failed", "items": nil, "total": 10, "next": 1})
		}
//line cmd/gopcomm/community_yap.gox:554:1
		uid := ctx.Param("uid")
//line cmd/gopcomm/community_yap.gox:555:1
		isPublic := ctx.Param("is_public")
//line cmd/gopcomm/community_yap.gox:556:1
		isPublicBool, err := strconv.ParseBool(isPublic)
//line cmd/gopcomm/community_yap.gox:557:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:558:1
			xLog.Error("parse bool error:", err)
//line cmd/gopcomm/community_yap.gox:559:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "parse bool failed"})
		}
//line cmd/gopcomm/community_yap.gox:565:1
		res, err := this.community.UpdateUserPublicAuth(uid, isPublicBool)
//line cmd/gopcomm/community_yap.gox:566:1
		if err != nil || !res {
//line cmd/gopcomm/community_yap.gox:567:1
			xLog.Info(err)
//line cmd/gopcomm/community_yap.gox:568:1
			ctx.Json__1(map[string]interface{}{"code": 0, "msg": "update failed"})
		}
//line cmd/gopcomm/community_yap.gox:574:1
		ctx.Json__1(map[string]int{"code": 200})
	})
//line cmd/gopcomm/community_yap.gox:579:1
	this.Get("/api/user/get-qrcode", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:580:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:581:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:582:1
			ctx.Json__1(map[string]int{"code": 500})
//line cmd/gopcomm/community_yap.gox:585:1
			return
		}
//line cmd/gopcomm/community_yap.gox:587:1
		gac, err := gopaccountsdk.GetClient(token.Value)
//line cmd/gopcomm/community_yap.gox:588:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:589:1
			ctx.Json__1(map[string]int{"code": 500})
//line cmd/gopcomm/community_yap.gox:592:1
			return
		}
//line cmd/gopcomm/community_yap.gox:594:1
		qrData, ticket, err := gac.GetProviderWeChatQRCode("provider_wechat")
//line cmd/gopcomm/community_yap.gox:595:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:596:1
			ctx.Json__1(map[string]int{"code": 500})
//line cmd/gopcomm/community_yap.gox:599:1
			return
		}
//line cmd/gopcomm/community_yap.gox:601:1
		ctx.Json__1(map[string]interface{}{"data": qrData, "data2": ticket, "code": 200})
	})
//line cmd/gopcomm/community_yap.gox:607:1
	this.Get("/api/user/acoount/unlink", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:608:1
		pv := ctx.Param("pv")
//line cmd/gopcomm/community_yap.gox:609:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:610:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:611:1
			ctx.Json__1(map[string]int{"code": 200})
//line cmd/gopcomm/community_yap.gox:614:1
			return
		}
//line cmd/gopcomm/community_yap.gox:616:1
		switch pv {
//line cmd/gopcomm/community_yap.gox:617:1
		case "Twitter":
//line cmd/gopcomm/community_yap.gox:618:1
		case "Facebook":
//line cmd/gopcomm/community_yap.gox:619:1
		case "Github":
//line cmd/gopcomm/community_yap.gox:620:1
		case "WeChat":
//line cmd/gopcomm/community_yap.gox:621:1
		default:
//line cmd/gopcomm/community_yap.gox:622:1
			pv = ""
		}
//line cmd/gopcomm/community_yap.gox:624:1
		gac, err := gopaccountsdk.GetClient(token.Value)
//line cmd/gopcomm/community_yap.gox:625:1
		if err == nil {
//line cmd/gopcomm/community_yap.gox:626:1
			gac.UnLink(pv)
		}
//line cmd/gopcomm/community_yap.gox:628:1
		ctx.Json__1(map[string]int{"code": 200})
	})
//line cmd/gopcomm/community_yap.gox:633:1
	this.Get("/api/user/:id/articles", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:634:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:635:1
		page := ctx.Param("page")
//line cmd/gopcomm/community_yap.gox:636:1
		limit := ctx.Param("limit")
//line cmd/gopcomm/community_yap.gox:638:1
		limitInt, err := strconv.Atoi(limit)
//line cmd/gopcomm/community_yap.gox:639:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:640:1
			limitInt = mediaLimitConst
		}
//line cmd/gopcomm/community_yap.gox:642:1
		items, total, err := this.community.GetArticlesByUid(todo, id, page, limitInt)
//line cmd/gopcomm/community_yap.gox:643:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:644:1
			xLog.Error("get article list error:", err)
//line cmd/gopcomm/community_yap.gox:645:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": err.Error(), "total": 0})
		}
//line cmd/gopcomm/community_yap.gox:651:1
		ctx.Json__1(map[string]interface{}{"code": 200, "items": items, "total": total})
	})
//line cmd/gopcomm/community_yap.gox:658:1
	this.Get("/api/user/:id/medias", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:659:1
		format := ctx.Param("format")
//line cmd/gopcomm/community_yap.gox:660:1
		uid := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:661:1
		page := ctx.Param("page")
//line cmd/gopcomm/community_yap.gox:662:1
		limit := ctx.Param("limit")
//line cmd/gopcomm/community_yap.gox:664:1
		limitInt, err := strconv.Atoi(limit)
//line cmd/gopcomm/community_yap.gox:665:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:666:1
			limitInt = mediaLimitConst
		}
//line cmd/gopcomm/community_yap.gox:668:1
		pageInt, err := strconv.Atoi(page)
//line cmd/gopcomm/community_yap.gox:669:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:670:1
			ctx.Json__1(map[string]interface{}{"code": 400, "total": 0, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:676:1
		files, total, err := this.community.ListMediaByUserId(todo, uid, format, pageInt, limitInt)
//line cmd/gopcomm/community_yap.gox:677:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:678:1
			ctx.Json__1(map[string]interface{}{"code": 0, "total": total, "err": err.Error()})
		} else {
//line cmd/gopcomm/community_yap.gox:684:1
			ctx.Json__1(map[string]interface{}{"code": 200, "total": total, "items": files})
		}
	})
//line cmd/gopcomm/community_yap.gox:695:1
	this.Delete("/api/media/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:696:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:697:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:698:1
		uid, err := this.community.ParseJwtToken(token.Value)
//line cmd/gopcomm/community_yap.gox:699:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:700:1
			xLog.Error("token parse error")
//line cmd/gopcomm/community_yap.gox:701:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:706:1
		err = this.community.DelMedia(todo, uid, id)
//line cmd/gopcomm/community_yap.gox:707:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:708:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "delete failed"})
		} else {
//line cmd/gopcomm/community_yap.gox:713:1
			ctx.Json__1(map[string]interface{}{"code": 200, "msg": "delete success"})
		}
	})
//line cmd/gopcomm/community_yap.gox:720:1
	this.Get("/api/translation/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:721:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:722:1
		article, err := this.community.GetTranslateArticle(todo, id)
//line cmd/gopcomm/community_yap.gox:724:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:725:1
			xLog.Info(err)
//line cmd/gopcomm/community_yap.gox:726:1
			ctx.Json__1(map[string]int{"code": 0})
		}
//line cmd/gopcomm/community_yap.gox:730:1
		ctx.Json__1(map[string]interface{}{"code": 200, "content": article.Content, "tags": article.Tags, "title": article.Title})
	})
//line cmd/gopcomm/community_yap.gox:738:1
	this.Post("/api/translation", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:739:1
		mdData := ctx.Param("content")
//line cmd/gopcomm/community_yap.gox:740:1
		transData, err := this.community.TranslateMarkdownText(todo, mdData, "auto", language.English)
//line cmd/gopcomm/community_yap.gox:741:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:742:1
			ctx.Json__1(map[string]interface{}{"code": 500, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:747:1
		ctx.Json__1(map[string]interface{}{"code": 200, "data": transData})
	})
//line cmd/gopcomm/community_yap.gox:753:1
	this.Get("/api/media/:id/url", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:754:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:755:1
		fileKey, err := this.community.GetMediaUrl(todo, id)
//line cmd/gopcomm/community_yap.gox:756:1
		htmlUrl := fmt.Sprintf("%s%s", this.domain, fileKey)
//line cmd/gopcomm/community_yap.gox:757:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:758:1
			ctx.Json__1(map[string]interface{}{"code": 500, "err": "have no html media"})
		}
//line cmd/gopcomm/community_yap.gox:763:1
		ctx.Json__1(map[string]interface{}{"code": 200, "url": htmlUrl})
	})
//line cmd/gopcomm/community_yap.gox:769:1
	this.Get("/api/video/:id", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:770:1
		id := ctx.Param("id")
//line cmd/gopcomm/community_yap.gox:771:1
		fileKey, err := this.community.GetMediaUrl(todo, id)
//line cmd/gopcomm/community_yap.gox:772:1
		m := make(map[string]string, 4)
//line cmd/gopcomm/community_yap.gox:773:1
		format, err := this.community.GetMediaType(todo, id)
//line cmd/gopcomm/community_yap.gox:774:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:775:1
			ctx.Json__1(map[string]interface{}{"code": 500, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:780:1
		htmlUrl := fmt.Sprintf("%s%s", this.domain, fileKey)
//line cmd/gopcomm/community_yap.gox:781:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:782:1
			ctx.Json__1(map[string]interface{}{"code": 500, "err": "have no html media"})
		}
//line cmd/gopcomm/community_yap.gox:787:1
		m["fileKey"] = htmlUrl
//line cmd/gopcomm/community_yap.gox:788:1
		m["type"] = format
//line cmd/gopcomm/community_yap.gox:789:1
		m["subtitle"] = this.domain + id
//line cmd/gopcomm/community_yap.gox:790:1
		m["status"] = "0"
//line cmd/gopcomm/community_yap.gox:791:1
		match, _ := regexp.MatchString("^video", format)
//line cmd/gopcomm/community_yap.gox:792:1
		if match {
//line cmd/gopcomm/community_yap.gox:793:1
			subtitle, status, err := this.community.GetVideoSubtitle(todo, id)
//line cmd/gopcomm/community_yap.gox:794:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:795:1
				ctx.Json__1(map[string]interface{}{"code": 200, "url": m})
			}
//line cmd/gopcomm/community_yap.gox:800:1
			if status == "1" {
//line cmd/gopcomm/community_yap.gox:801:1
				m["subtitle"] = this.domain + subtitle
			}
//line cmd/gopcomm/community_yap.gox:803:1
			m["status"] = status
		}
//line cmd/gopcomm/community_yap.gox:805:1
		ctx.Json__1(map[string]interface{}{"code": 200, "url": m})
	})
//line cmd/gopcomm/community_yap.gox:811:1
	this.Post("/api/media", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:812:1
		xLog := xlog.New("")
//line cmd/gopcomm/community_yap.gox:813:1
		file, header, err := ctx.FormFile("file")
//line cmd/gopcomm/community_yap.gox:814:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:815:1
			xLog.Error("upload file error:", header)
//line cmd/gopcomm/community_yap.gox:816:1
			ctx.JSON(500, err.Error())
//line cmd/gopcomm/community_yap.gox:817:1
			return
		}
//line cmd/gopcomm/community_yap.gox:819:1
		filename := header.Filename
//line cmd/gopcomm/community_yap.gox:820:1
		err = ctx.ParseMultipartForm(10 << 20)
//line cmd/gopcomm/community_yap.gox:821:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:822:1
			xLog.Error("upload file error:", filename)
//line cmd/gopcomm/community_yap.gox:823:1
			ctx.JSON(500, err.Error())
//line cmd/gopcomm/community_yap.gox:824:1
			return
		}
//line cmd/gopcomm/community_yap.gox:827:1
		dst, err := os.Create(filename)
//line cmd/gopcomm/community_yap.gox:828:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:829:1
			xLog.Error("create file error:", file)
//line cmd/gopcomm/community_yap.gox:830:1
			ctx.JSON(500, err.Error())
//line cmd/gopcomm/community_yap.gox:831:1
			return
		}
//line cmd/gopcomm/community_yap.gox:833:1
		defer func() {
//line cmd/gopcomm/community_yap.gox:834:1
			file.Close()
//line cmd/gopcomm/community_yap.gox:835:1
			dst.Close()
//line cmd/gopcomm/community_yap.gox:836:1
			err = os.Remove(filename)
//line cmd/gopcomm/community_yap.gox:837:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:838:1
				xLog.Error("delete file error:", filename)
//line cmd/gopcomm/community_yap.gox:839:1
				return
			}
		}()
//line cmd/gopcomm/community_yap.gox:843:1
		_, err = io.Copy(dst, file)
//line cmd/gopcomm/community_yap.gox:844:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:845:1
			xLog.Error("copy file errer:", filename)
//line cmd/gopcomm/community_yap.gox:846:1
			ctx.JSON(500, err.Error())
//line cmd/gopcomm/community_yap.gox:847:1
			return
		}
//line cmd/gopcomm/community_yap.gox:850:1
		bytes, err := os.ReadFile(filename)
//line cmd/gopcomm/community_yap.gox:851:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:852:1
			xLog.Error("read file errer:", filename)
//line cmd/gopcomm/community_yap.gox:853:1
			ctx.JSON(500, err.Error())
//line cmd/gopcomm/community_yap.gox:854:1
			return
		}
//line cmd/gopcomm/community_yap.gox:857:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:858:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:859:1
			ctx.JSON(500, err.Error())
		}
//line cmd/gopcomm/community_yap.gox:862:1
		uid, err := this.community.ParseJwtToken(token.Value)
//line cmd/gopcomm/community_yap.gox:863:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:864:1
			ctx.JSON(500, err.Error())
		}
//line cmd/gopcomm/community_yap.gox:866:1
		ext := mimetype.Detect(bytes).String()
//line cmd/gopcomm/community_yap.gox:867:1
		id, err := this.community.SaveMedia(context.Background(), uid, bytes, ext)
//line cmd/gopcomm/community_yap.gox:868:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:869:1
			xLog.Error("save file", err.Error())
//line cmd/gopcomm/community_yap.gox:870:1
			ctx.JSON(500, err.Error())
//line cmd/gopcomm/community_yap.gox:871:1
			return
		}
//line cmd/gopcomm/community_yap.gox:875:1
		if strings.Contains(ext, "video") {
//line cmd/gopcomm/community_yap.gox:877:1
			err := this.community.NewVideoTask(context.Background(), uid, strconv.FormatInt(id, 10))
//line cmd/gopcomm/community_yap.gox:878:1
			if err != nil {
//line cmd/gopcomm/community_yap.gox:879:1
				xLog.Error("start video task error:", err)
			}
		}
//line cmd/gopcomm/community_yap.gox:883:1
		ctx.JSON(200, id)
	})
//line cmd/gopcomm/community_yap.gox:886:1
	this.Post("/api/caption/task", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:887:1
		uid := ctx.Param("uid")
//line cmd/gopcomm/community_yap.gox:888:1
		vid := ctx.Param("vid")
//line cmd/gopcomm/community_yap.gox:890:1
		if uid == "" || vid == "" {
//line cmd/gopcomm/community_yap.gox:891:1
			ctx.Json__1(map[string]interface{}{"code": 200, "msg": "Invalid param"})
		}
//line cmd/gopcomm/community_yap.gox:897:1
		if
//line cmd/gopcomm/community_yap.gox:897:1
		err := this.community.RetryCaptionGenerate(todo, uid, vid); err != nil {
//line cmd/gopcomm/community_yap.gox:898:1
			ctx.Json__1(map[string]interface{}{"code": 200, "msg": "Request task error"})
		}
//line cmd/gopcomm/community_yap.gox:904:1
		ctx.Json__1(map[string]interface{}{"code": 200, "msg": "Ok"})
	})
//line cmd/gopcomm/community_yap.gox:913:1
	this.Get("/login", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:918:1
		refererURL, err := url.Parse(ctx.Request.Referer())
//line cmd/gopcomm/community_yap.gox:919:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:920:1
			xLog.Infof("Error parsing Referer: %#v", err)
//line cmd/gopcomm/community_yap.gox:921:1
			return
		}
//line cmd/gopcomm/community_yap.gox:924:1
		refererPath := refererURL.Path
//line cmd/gopcomm/community_yap.gox:925:1
		if refererURL.RawQuery != "" {
//line cmd/gopcomm/community_yap.gox:926:1
			refererPath = fmt.Sprintf("%s?%s", refererURL.Path, refererURL.RawQuery)
		}
//line cmd/gopcomm/community_yap.gox:929:1
		redirectURL := fmt.Sprintf("%s://%s/%s?origin_path=%s", refererURL.Scheme, refererURL.Host, "login/callback", url.QueryEscape(refererPath))
//line cmd/gopcomm/community_yap.gox:931:1
		loginURL := this.community.RedirectToCasdoor(redirectURL)
//line cmd/gopcomm/community_yap.gox:932:1
		ctx.Redirect(loginURL, http.StatusFound)
	})
//line cmd/gopcomm/community_yap.gox:935:1
	this.Get("/logout", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:936:1
		tokenCookie, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:937:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:938:1
			xLog.Error("remove token error:", err)
//line cmd/gopcomm/community_yap.gox:939:1
			return
		}
//line cmd/gopcomm/community_yap.gox:942:1
		tokenCookie.MaxAge = -1
//line cmd/gopcomm/community_yap.gox:943:1
		http.SetCookie(ctx.ResponseWriter, tokenCookie)
//line cmd/gopcomm/community_yap.gox:945:1
		refererURL, err := url.Parse(ctx.Request.Referer())
//line cmd/gopcomm/community_yap.gox:946:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:947:1
			xLog.Infof("Error parsing Referer: %#v", err)
//line cmd/gopcomm/community_yap.gox:948:1
			return
		}
//line cmd/gopcomm/community_yap.gox:951:1
		refererPath := refererURL.Path
//line cmd/gopcomm/community_yap.gox:952:1
		if refererURL.RawQuery != "" {
//line cmd/gopcomm/community_yap.gox:953:1
			refererPath = fmt.Sprintf("%s?%s", refererURL.Path, refererURL.RawQuery)
		}
//line cmd/gopcomm/community_yap.gox:956:1
		http.Redirect(ctx.ResponseWriter, ctx.Request, refererPath, http.StatusFound)
	})
//line cmd/gopcomm/community_yap.gox:959:1
	this.Get("/login/callback", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:960:1
		code := ctx.URL.Query().Get("code")
//line cmd/gopcomm/community_yap.gox:961:1
		state := ctx.URL.Query().Get("state")
//line cmd/gopcomm/community_yap.gox:962:1
		token, err := this.community.GetOAuthToken(code, state)
//line cmd/gopcomm/community_yap.gox:963:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:964:1
			xLog.Error("set token error:", err)
		}
//line cmd/gopcomm/community_yap.gox:966:1
		cookie := http.Cookie{Name: "token", Value: token.AccessToken, Path: "/", MaxAge: 168 * 60 * 60, HttpOnly: true}
//line cmd/gopcomm/community_yap.gox:973:1
		http.SetCookie(ctx.ResponseWriter, &cookie)
//line cmd/gopcomm/community_yap.gox:975:1
		origin_path := ctx.URL.Query().Get("origin_path")
//line cmd/gopcomm/community_yap.gox:976:1
		unurl, err := url.QueryUnescape(origin_path)
//line cmd/gopcomm/community_yap.gox:977:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:978:1
			xLog.Info("Unurl error", err)
//line cmd/gopcomm/community_yap.gox:979:1
			unurl = "/"
		}
//line cmd/gopcomm/community_yap.gox:982:1
		http.Redirect(ctx.ResponseWriter, ctx.Request, unurl, http.StatusFound)
	})
//line cmd/gopcomm/community_yap.gox:985:1
	this.Post("/api/article/like", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:986:1
		articleId := ctx.Param("articleId")
//line cmd/gopcomm/community_yap.gox:987:1
		articleIdInt, err := strconv.Atoi(articleId)
//line cmd/gopcomm/community_yap.gox:988:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:989:1
			ctx.Json__1(map[string]interface{}{"code": 500, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:994:1
		token, err := ctx.Request.Cookie("token")
//line cmd/gopcomm/community_yap.gox:995:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:996:1
			xLog.Info("token", err)
//line cmd/gopcomm/community_yap.gox:997:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": "no token"})
		}
//line cmd/gopcomm/community_yap.gox:1002:1
		uid, err := this.community.ParseJwtToken(token.Value)
//line cmd/gopcomm/community_yap.gox:1003:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:1004:1
			ctx.Json__1(map[string]interface{}{"code": 0, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:1009:1
		res, err := this.community.ArticleLike(todo, articleIdInt, uid)
//line cmd/gopcomm/community_yap.gox:1010:1
		if err != nil {
//line cmd/gopcomm/community_yap.gox:1011:1
			ctx.Json__1(map[string]interface{}{"code": 500, "err": err.Error()})
		}
//line cmd/gopcomm/community_yap.gox:1016:1
		ctx.Json__1(map[string]interface{}{"code": 200, "data": res})
	})
//line cmd/gopcomm/community_yap.gox:1023:1
	this.Handle("/", func(ctx *yap.Context) {
//line cmd/gopcomm/community_yap.gox:1024:1
		ctx.Yap__1("4xx", map[string]interface{}{})
	})
//line cmd/gopcomm/community_yap.gox:1027:1
	configFile := ".env"
//line cmd/gopcomm/community_yap.gox:1028:1
	flag.StringVar(&configFile, "config", ".env", "Path to the config file")
//line cmd/gopcomm/community_yap.gox:1029:1
	flag.Parse()
//line cmd/gopcomm/community_yap.gox:1030:1
	if
//line cmd/gopcomm/community_yap.gox:1030:1
	err := godotenv.Load(configFile); err != nil {
//line cmd/gopcomm/community_yap.gox:1031:1
		xLog.Error(err)
	}
//line cmd/gopcomm/community_yap.gox:1034:1
	conf := core.NewConfigFromEnv()
//line cmd/gopcomm/community_yap.gox:1035:1
	this.community, _ = core.New(todo, conf)
//line cmd/gopcomm/community_yap.gox:1036:1
	this.domain = conf.QiNiuConfig.Domain
//line cmd/gopcomm/community_yap.gox:1037:1
	endpoint := conf.AppConfig.EndPoint
//line cmd/gopcomm/community_yap.gox:1039:1
	xLog.Info("Started in endpoint: ", endpoint)
//line cmd/gopcomm/community_yap.gox:1042:1
	this.Run(endpoint, func(h http.Handler) http.Handler {
//line cmd/gopcomm/community_yap.gox:1044:1
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
//line cmd/gopcomm/community_yap.gox:1045:1
			defer func() {
//line cmd/gopcomm/community_yap.gox:1047:1
				if
//line cmd/gopcomm/community_yap.gox:1047:1
				err := recover(); err != nil {
//line cmd/gopcomm/community_yap.gox:1048:1
					xLog.Error(err)
//line cmd/gopcomm/community_yap.gox:1049:1
					http.Redirect(w, r, "/failed", http.StatusFound)
				}
			}()
//line cmd/gopcomm/community_yap.gox:1053:1
			h.ServeHTTP(w, r)
		})
	})
}
func main() {
	yap.Gopt_App_Main(new(community))
}
