// Code generated by gop (Go+); DO NOT EDIT.

package markdown

const _ = true

//line markdown/render.gop:19:1
// Render renders a markdown text into html.
func Render(md string) (html string, err error) {
//line markdown/render.gop:21:1
	return md, nil
}
