package core

import (
	"context"
	"encoding/json"
	"testing"
)

func TestGetApplicationInfo(t *testing.T) {
	conf := &Config{}
	todo := context.TODO()
	community, err := New(todo, conf)

	if err != nil {
		t.Skip(err)
	}
	a, _ := community.GetApplicationInfo()
	b, err := json.Marshal(*a)
	t.Log(string(b), err)
}

const token = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlcnQtYnVpbHQtaW4iLCJ0eXAiOiJKV1QifQ.eyJvd25lciI6IkdvUGx1cyIsIm5hbWUiOiJDcmFmdExpdXMiLCJjcmVhdGVkVGltZSI6IjIwMjQtMDItMTlUMDM6MjI6MDRaIiwidXBkYXRlZFRpbWUiOiIyMDI0LTAyLTE5VDEwOjA1OjUxWiIsImRlbGV0ZWRUaW1lIjoiIiwiaWQiOiIxMjI0NDA1OTIwMjYxNjIzODA5IiwidHlwZSI6Im5vcm1hbC11c2VyIiwicGFzc3dvcmQiOiIiLCJwYXNzd29yZFNhbHQiOiIiLCJwYXNzd29yZFR5cGUiOiJwbGFpbiIsImRpc3BsYXlOYW1lIjoiZHJnZ2R3ZWFmYSIsImZpcnN0TmFtZSI6IiIsImxhc3ROYW1lIjoiIiwiYXZhdGFyIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzQ3MDYyODMyP3Y9NCIsImF2YXRhclR5cGUiOiIiLCJwZXJtYW5lbnRBdmF0YXIiOiIiLCJlbWFpbCI6IiIsImVtYWlsVmVyaWZpZWQiOmZhbHNlLCJwaG9uZSI6IiIsImNvdW50cnlDb2RlIjoiIiwicmVnaW9uIjoiIiwibG9jYXRpb24iOiIiLCJhZGRyZXNzIjpbXSwiYWZmaWxpYXRpb24iOiIiLCJ0aXRsZSI6IiIsImlkQ2FyZFR5cGUiOiIiLCJpZENhcmQiOiIiLCJob21lcGFnZSI6IiIsImJpbyI6IiIsImxhbmd1YWdlIjoiIiwiZ2VuZGVyIjoiIiwiYmlydGhkYXkiOiIiLCJlZHVjYXRpb24iOiIiLCJzY29yZSI6MCwia2FybWEiOjAsInJhbmtpbmciOjcsImlzRGVmYXVsdEF2YXRhciI6ZmFsc2UsImlzT25saW5lIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlzRm9yYmlkZGVuIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwic2lnbnVwQXBwbGljYXRpb24iOiJhcHBsaWNhdGlvbl94OGFldmsiLCJoYXNoIjoiIiwicHJlSGFzaCI6IiIsImFjY2Vzc0tleSI6IiIsImFjY2Vzc1NlY3JldCI6IiIsImdpdGh1YiI6IjQ3MDYyODMyIiwiZ29vZ2xlIjoiIiwicXEiOiIiLCJ3ZWNoYXQiOiIiLCJmYWNlYm9vayI6IiIsImRpbmd0YWxrIjoiIiwid2VpYm8iOiIiLCJnaXRlZSI6IiIsImxpbmtlZGluIjoiIiwid2Vjb20iOiIiLCJsYXJrIjoiIiwiZ2l0bGFiIjoiIiwiY3JlYXRlZElwIjoiIiwibGFzdFNpZ25pblRpbWUiOiIiLCJsYXN0U2lnbmluSXAiOiIiLCJwcmVmZXJyZWRNZmFUeXBlIjoiIiwicmVjb3ZlcnlDb2RlcyI6bnVsbCwidG90cFNlY3JldCI6IiIsIm1mYVBob25lRW5hYmxlZCI6ZmFsc2UsIm1mYUVtYWlsRW5hYmxlZCI6ZmFsc2UsImxkYXAiOiIiLCJwcm9wZXJ0aWVzIjp7Im5vIjoiOCIsIm9hdXRoX0dpdEh1Yl9hdmF0YXJVcmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvNDcwNjI4MzI_dj00Iiwib2F1dGhfR2l0SHViX2Rpc3BsYXlOYW1lIjoiTGl1c0NyYWZ0Iiwib2F1dGhfR2l0SHViX2lkIjoiNDcwNjI4MzIiLCJvYXV0aF9HaXRIdWJfdXNlcm5hbWUiOiJMaXVzQ3JhZnQiLCJvYXV0aF9Ud2l0dGVyX2Rpc3BsYXlOYW1lIjoiZHJnZ2R3ZWFmYSIsIm9hdXRoX1R3aXR0ZXJfaWQiOiIxMjI0NDA1OTIwMjYxNjIzODA5Iiwib2F1dGhfVHdpdHRlcl91c2VybmFtZSI6IkNyYWZ0TGl1cyJ9LCJyb2xlcyI6W10sInBlcm1pc3Npb25zIjpbXSwiZ3JvdXBzIjpbXSwibGFzdFNpZ25pbldyb25nVGltZSI6IiIsInNpZ25pbldyb25nVGltZXMiOjAsInRva2VuVHlwZSI6ImFjY2Vzcy10b2tlbiIsInRhZyI6IiIsInNjb3BlIjoicmVhZCIsImlzcyI6Imh0dHBzOi8vY2FzZG9vci1jb21tdW5pdHkucWluaXUuaW8iLCJzdWIiOiIxMjI0NDA1OTIwMjYxNjIzODA5IiwiYXVkIjpbIjM4OTMxM2RmNTFmZmQyMDkzYjJmIl0sImV4cCI6MTcwODk0MTk1MSwibmJmIjoxNzA4MzM3MTUxLCJpYXQiOjE3MDgzMzcxNTEsImp0aSI6ImFkbWluL2MxYTE1ZDJkLWE1MGItNDc1MS1hN2JlLTRlYTFhZGU2MjBjOCJ9.SuS-I4QoBhgPXv7sUZoWIwSZvavupZgos_6cZNh-MkJD6DUd_87enT16NlSL-nqZ9hTN0cZUJOpjTmhmUEq-L8CZAp9dN_uJwN-l5VUIwIJAhI4l0jhNXmrO5Y7yaoI0qTbg21MmeLpyuN9KPIFBjB7iwlnXI43iiYcUn01rmlbi-8x5MVlOdpdGH_KfgGbHo_S7GanLk8bHCagMdEfQUFRwjO-n2czVN5LqbSCBGvOxKss1zerrlzMuvZwfust6PYhpmsXyTMu_brWn5NOyj5YUlbAP8YDaWTTqjwIglEloWB95elLwFACxe7eS_sRDWlfa9yS6d-1coIBg5WdGV_3LfeQKW7HwB9xvjgqsoewH62ulgYRJp8HcI8L26V_aSkn94eCxRK_iF-9egSfDmCuS07rfScLxokztkMpnuGEThsDF9Cwm5ttP-6DvlP5uPjKO_zWVMig-2jmah_c85zMi7ELiMTpVl2EfY3PxrBrhh__QpWt22Y6g8Dc3FLSbUOGz_iYISpTg6Cq1u9a_F0oHH_q0xnuAmP_DrKpYIPm829wFR1_6mmajCzvr1blDutIkM8ebYroZPwEZEqlnT_2eSaPIrOVqvLd_56Du9dy8OkRL01dbjUsAbmshDbGrGm4nMBpJsH6E16XM9_R6BcWyB703AotIFD_ZqKUjPS0"

func TestGetAccountBinds(t *testing.T) {
	conf := &Config{}
	todo := context.TODO()
	community, err := New(todo, conf)
	if err != nil {
		t.Skip(err)
	}
	t.Log(community.GetAccountBinds(token))
}

func TestAccountUnLink(t *testing.T) {
	conf := &Config{}
	todo := context.TODO()
	community, err := New(todo, conf)
	if err != nil {
		t.Skip(err)
	}
	t.Log(community.UnLink(token, "Twitter"))
}
